In [3]:
from functions_lib import summary, first_looking, missing_values, duplicate_values, multicolinearity_control, drop_columns, drop_null, shape_control, shape

In [4]:
df0 = pd.read_csv("train.csv", low_memory=False)

df = df0.copy()
df.head()
first_looking(df)
duplicate_values(df)
drop_columns(df,[])
drop_null(df, 90)

Shape:(2048109, 24)
****************************************************************************************************
Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2048109 entries, 0 to 2048108
Data columns (total 24 columns):
 #   Column                Dtype
---  ------                -----
 0   City                  object
 1   CustomerId            object
 2   VehicleId             object
 3   FirstRegistiration    object
 4   Make                  object
 5   BodyCode              object
 6   Serie                 object
 7   ModelCode             object
 8   ModelYear             int64
 9   InvoiceDate           object
 10  ServiceInvoiceDate    object
 11  BranchCode            int64
 12  Milage                int64
 13  MainGroupDescription  object
 14  SubGroupDescription   object
 15  SplitCode             object
 16  Split_Grubu           object
 17  ServiceInvoiceLineNo  object
 18  ItemDescription       object
 19  ItemNo                object
 20  ItemType              object
 21  MainGroupCode         object
 22  SubGroupCode          object
 23  IsMalfunction         int64
dtypes: int64(4), object(20)
memory usage: 375.0+ MB
None
****************************************************************************************************
Number of Uniques:
City                        21
CustomerId               45185
VehicleId                52424
FirstRegistiration        1977
Make                         4
BodyCode                    15
Serie                       11
ModelCode                  116
ModelYear                    7
InvoiceDate               2161
ServiceInvoiceDate      209095
BranchCode                  53
Milage                   77049
MainGroupDescription       108
SubGroupDescription        462
SplitCode                   56
Split_Grubu                  3
ServiceInvoiceLineNo       253
ItemDescription          13285
ItemNo                   23051
ItemType                     3
MainGroupCode               63
SubGroupCode                81
IsMalfunction                2
dtype: int64
****************************************************************************************************
Missing Values:
                    Missing_Number  Missing_Percent
FirstRegistiration            7403     3.614554e-03
CustomerId                     521     2.543810e-04
Serie                          160     7.812084e-05
ItemDescription                 27     1.318289e-05
ItemNo                           1     4.882553e-07
****************************************************************************************************
All Columns:
- City
- CustomerId
- VehicleId
- FirstRegistiration
- Make
- BodyCode
- Serie
- ModelCode
- ModelYear
- InvoiceDate
- ServiceInvoiceDate
- BranchCode
- Milage
- MainGroupDescription
- SubGroupDescription
- SplitCode
- Split_Grubu
- ServiceInvoiceLineNo
- ItemDescription
- ItemNo
- ItemType
- MainGroupCode
- SubGroupCode
- IsMalfunction
****************************************************************************************************
Columns after rename:
- city
- customerid
- vehicleid
- firstregistiration
- make
- bodycode
- serie
- modelcode
- modelyear
- invoicedate
- serviceinvoicedate
- branchcode
- milage
- maingroupdescription
- subgroupdescription
- splitcode
- split_grubu
- serviceinvoicelineno
- itemdescription
- itemno
- itemtype
- maingroupcode
- subgroupcode
- ismalfunction
****************************************************************************************************
Duplicate check...
There are no duplicates
****************************************************************************************************
Missing value control...
If there is a missing value above the limit you have given, the relevant columns are dropped and an information is given.
Last shape after missing value control:(2048109, 24)
****************************************************************************************************

In [10]:
df.head()

,city,customerid,vehicleid,firstregistiration,make,bodycode,serie,modelcode,modelyear,invoicedate,...,subgroupdescription,splitcode,split_grubu,serviceinvoicelineno,itemdescription,itemno,itemtype,maingroupcode,subgroupcode,ismalfunction
0,Muğla,10393975,02i0Y000005Htw6QAC,2018-04-27,BMW,F48,BMW X1,JH11,2018,2021-12-31 00:00:00,...,Belirsiz,16,other,160000,LİFT TAKOZU,51717123311,Parça,01,Belirsiz,0
1,İstanbul,10817259,02i1i000007CkokAAC,2020-09-24,BMW,F40,BMW 1 Serisi,7M71,2020,2021-12-29 00:00:00,...,Belirsiz,1,other,140000,SARF MALZEMESİ,99990601200,Parça,Belirsiz,Belirsiz,0
2,İstanbul,10330911,02i0Y000007Xft3QAC,2018-05-25,BMW,G30,BMW 5 Serisi,JA31,2018,2018-10-05 00:00:00,...,Belirsiz,85,other,220000,MALZEME,99990000004,Parça,Belirsiz,Belirsiz,0
3,İzmir,1157429,02i1i000005k7yeAAA,2020-04-10,BMW,F40,BMW 1 Serisi,7M71,2020,2020-11-02 00:00:00,...,Sabitlemeli marş motoru,21,other,70000,Marş Motorunun Sökülmesi Ve Takılması/,1241520,İşçilik,12,41,0
4,Bursa,912355,02i0Y000007Xkk8QAC,2018-05-29,BMW,G30,BMW 5 Serisi,JA71,2018,2021-04-01 00:00:00,...,Ön cam sileceği,16,other,490000,Her İki Silecek Last.değiştirilmesi,6161541,İşçilik,61,61,0

In [11]:
df.tail()

,city,customerid,vehicleid,firstregistiration,make,bodycode,serie,modelcode,modelyear,invoicedate,...,subgroupdescription,splitcode,split_grubu,serviceinvoicelineno,itemdescription,itemno,itemtype,maingroupcode,subgroupcode,ismalfunction
2048104,Ankara,360469,02i0Y000005HubdQAC,2018-07-03,BMW,G30,BMW 5 Serisi,JC51,2018,2021-06-25 00:00:00,...,Belirsiz,52,Hasar,540000,ALT HAVA KANALI,51137497285,Parça,01,Belirsiz,0
2048105,İstanbul,1157429,02i0Y000004hxxOQAQ,2016-01-04,BMW,G11,BMW 7 Serisi,7A01,2015,2016-01-18 00:00:00,...,Belirsiz,5,other,130000,Bmw & Bmw-Mını Oto Yıkama,75,Harici İşçilik,Belirsiz,Belirsiz,0
2048106,Ankara,1161346,02i0Y000004hEKWQA2,2017-12-11,BMW,G30,BMW 5 Serisi,JA31,2017,2018-05-09 00:00:00,...,Belirsiz,4,other,60000,ÖN FREN BALA,34106884492,Parça,Belirsiz,Belirsiz,0
2048107,İstanbul,1163007,02i0Y000004hHFHQA2,2018-04-11,BMW,G11,BMW 7 Serisi,7A01,2017,2018-08-17 00:00:00,...,Belirsiz,1,other,280000,BMW ATF 3,83222289720Y,Parça,Belirsiz,Belirsiz,0
2048108,Ankara,360469,02i0Y000004h6DoQAI,2016-12-01,MINI,F55,MINI Hatch,XT31,2016,2018-11-26 00:00:00,...,Belirsiz,11,other,310000,SİLECEK SİSTEMİ HORTUM ONARIM,61667208073,Parça,Belirsiz,Belirsiz,0

In [12]:
df.sample(5)

,city,customerid,vehicleid,firstregistiration,make,bodycode,serie,modelcode,modelyear,invoicedate,...,subgroupdescription,splitcode,split_grubu,serviceinvoicelineno,itemdescription,itemno,itemtype,maingroupcode,subgroupcode,ismalfunction
1278825,İstanbul,620136,02i0Y000004hl01QAA,2016-01-02,BMW,F48,BMW X1,HU31,2015,2020-06-03 00:00:00,...,Belirsiz,16,other,210000,HAVA FİLTRESİ,13718513944,Parça,Belirsiz,Belirsiz,0
495033,Mersin,1017331,02i0Y000004hKpSQAU,2017-07-06,BMW,G30,BMW 5 Serisi,JA71,2017,2021-04-16 00:00:00,...,Belirsiz,12,other,50000,Verisi Olmayan İşçilik Süresi/ön Aks,3199000,İşçilik,31,99,0
2030776,İzmir,10238081,02i0Y000004fy5tQAA,2017-12-01,BMW,G30,BMW 5 Serisi,JA31,2017,2021-11-05 00:00:00,...,Belirsiz,1,other,230000,BMW ORIJINAL CAM SUYU KATKISI,83125A1A174,Parça,Belirsiz,Belirsiz,0
1366965,İstanbul,360469,02i0Y000004hE6rQAE,2017-08-15,BMW,G30,BMW 5 Serisi,JA31,2017,2019-10-14 00:00:00,...,Denetimler,11,other,20000,Servisin Standart Kapsamı,0000105,İşçilik,00,00,0
150939,Kayseri,10687667,02i1i000000SK3yAAG,2019-09-02,BMW,F48,BMW X1,31AC,2019,2020-10-27 00:00:00,...,Belirsiz,1,other,350000,Mekanik İşlemler,20,Harici İşçilik,Belirsiz,Belirsiz,0

In [13]:
df.ismalfunction.value_counts()

0    2034757
1      13352
Name: ismalfunction, dtype: int64

In [15]:
df.ismalfunction.value_counts(normalize=True) * 100

0    99.348082
1     0.651918
Name: ismalfunction, dtype: float64

In [5]:
df.isnull().sum()

city                       0
customerid               521
vehicleid                  0
firstregistiration      7403
make                       0
bodycode                   0
serie                    160
modelcode                  0
modelyear                  0
invoicedate                0
serviceinvoicedate         0
branchcode                 0
milage                     0
maingroupdescription       0
subgroupdescription        0
splitcode                  0
split_grubu                0
serviceinvoicelineno       0
itemdescription           27
itemno                     1
itemtype                   0
maingroupcode              0
subgroupcode               0
ismalfunction              0
dtype: int64

In [7]:
df.groupby("vehicleid")["invoicedate"].value_counts()

vehicleid           invoicedate
02i0Y000004fqBXQAY  2019-09-06 00:00:00    12
                    2019-09-23 00:00:00     9
                    2017-12-28 00:00:00     8
                    2019-04-05 00:00:00     7
                    2018-11-01 00:00:00     1
                                           ..
02i1n00000OpcxCAAR  2020-06-23 00:00:00     3
                    2019-06-28 00:00:00     2
                    2019-11-04 00:00:00     2
                    2021-09-18 00:00:00     2
                    2021-10-20 00:00:00     2
Name: invoicedate, Length: 302037, dtype: int64

In [13]:
df.groupby("vehicleid")["invoicedate"].count().idxmax()

'02i0Y000004hKpSQAU'

In [16]:
df[(df["vehicleid"]=="02i0Y000004hKpSQAU")]['ismalfunction'].value_counts()

0    575
1      2
Name: ismalfunction, dtype: int64

In [18]:
df[(df["vehicleid"]=="02i0Y000004hKpSQAU")&(df["ismalfunction"]==1)].T

                                  787306               1516204
city                               Mersin               Mersin
customerid                        1017331              1017331
vehicleid              02i0Y000004hKpSQAU   02i0Y000004hKpSQAU
firstregistiration             2017-07-06           2017-07-06
make                                  BMW                  BMW
bodycode                              G30                  G30
serie                        BMW 5 Serisi         BMW 5 Serisi
modelcode                            JA71                 JA71
modelyear                            2017                 2017
invoicedate           2021-02-10 00:00:00  2021-04-16 00:00:00
serviceinvoicedate             SINP081758           SINP083228
branchcode                         133033               133033
milage                             244611               260104
maingroupdescription             Belirsiz             Belirsiz
subgroupdescription              Belirsiz             Belirsiz
splitcode                              16                   12
split_grubu                         other                other
serviceinvoicelineno               430000               210000
itemdescription                     TURBO           SU POMPASI
itemno                        11658631891          11518638026
itemtype                            Parça                Parça
maingroupcode                    Belirsiz             Belirsiz
subgroupcode                     Belirsiz             Belirsiz
ismalfunction                           1                    1

In [19]:
df[(df["vehicleid"]=="02i0Y000004hKpSQAU")&(df["ismalfunction"]==0)]["itemdescription"].value_counts()

MALZEME                        23
Servisin Standart Kapsamı      22
Tüm Fonksiyonların Kontrolü    22
YAĞ FİLTRESİ                   20
Motor Yağı Servisi             19
                               ..
KAPI FL                         1
Proceramic -  2 Cam Filmi       1
ÇAMURLUK FL                     1
ÇAMURLUK İZOLASYONU L           1
Radyatörü Değiştirme            1
Name: itemdescription, Length: 201, dtype: int64

In [44]:
a = df[(df["ismalfunction"]==1)]["itemdescription"].value_counts().index
a

Index(['V KAYIŞI', 'GERGİ BİLYASI', 'VIBRASYON DAMPER',
       'Dönel Titreşim Damperini Değiştirme', 'SU POMPASI', 'MOTOR ASKI ROTU',
       'KRANK SENSÖRÜ', 'TURBO', 'GENLEŞME TANKI', 'TURBO RADYATÖRÜ',
       'Dönel Titreşim Damperinin Değiştirilmesi', 'TİTREŞİM DAMPERİ',
       'Egzoz Gazı Turbo Ünitesi Soğutma Sıvısı', 'GERGI', 'SU POMPA KAYIŞI',
       'V KAYISI', 'GERGİ', 'V KAYIŞ', 'GERGI BILYAS'],
      dtype='object')

In [56]:
b = df[(df["ismalfunction"]==0)]["itemdescription"].value_counts().to_frame()
b

                                   itemdescription
Servisin Standart Kapsamı                   133961
YAĞ FİLTRESİ                                113110
Motor Yağı Servisi                          112427
Tüm Fonksiyonların Kontrolü                  56770
Mikro Filtre Servisi                         42625
...                                            ...
KAPUT LASTIĞ                                     1
Alt Yaya Korumasının Sökülmesi ve                1
KAPI DÖSEMESI FL                                 1
PANDİZOT KLİPSİ                                  1
SİLECEK SİSTEMİ HORTUM ONARIM                    1

[13266 rows x 1 columns]

In [57]:
b.isin(list(a[0])).sum()

itemdescription    0
dtype: int64

In [58]:
len(a)

19

In [59]:
c = []

for i in range(len(a)):
    if a[i] in b:
        c.append(a[i])
    else:
        pass

print(c)

[]

In [10]:
df[(df["vehicleid"]=="02i0Y000004fqBXQAY")&(df["invoicedate"]=="2019-09-06 00:00:00")]

,city,customerid,vehicleid,firstregistiration,make,bodycode,serie,modelcode,modelyear,invoicedate,...,subgroupdescription,splitcode,split_grubu,serviceinvoicelineno,itemdescription,itemno,itemtype,maingroupcode,subgroupcode,ismalfunction
174422,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,240000,AYNA CAMI L,51167366039,Parça,Belirsiz,Belirsiz,0
271295,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Denetimler,1,other,70000,Ön Frenin Servisi,0000612,İşçilik,00,00,0
282048,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,350000,Verisi Olmayan İşçilik Süresi/,3699000,İşçilik,36,99,0
547090,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,230000,ÖN KAPI CAM NİKELAJI L,51337322513,Parça,Belirsiz,Belirsiz,0
859597,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,220000,ARKA FREN İKAZ FİŞİ,34356865612,Parça,Belirsiz,Belirsiz,0
1148857,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,120000,ÖN FREN İKAZ FİŞİ,34356887827,Parça,Belirsiz,Belirsiz,0
1233689,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,210000,ARKA FREN BALATASI,34216871299,Parça,Belirsiz,Belirsiz,0
1238661,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Belirsiz,1,other,110000,ÖN FREN BALATASI,34106884263,Parça,Belirsiz,Belirsiz,0
1371410,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Yürüyen aksam ölçümü/ayarı,1,other,290000,Arka Ve Ön Aksın Ayarlanması,3200630,İşçilik,32,00,0
1442747,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Denetimler,1,other,20000,Servisin Standart Kapsamı,0000105,İşçilik,00,00,0
1479707,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Tekerlekler,1,other,340000,Jant Radyal Kaçıklığının Ve Yanal,3610715,İşçilik,36,10,0
1927255,İzmir,10488807,02i0Y000004fqBXQAY,2017-12-04,MINI,F55,MINI Hatch,XT31,2017,2019-09-06 00:00:00,...,Denetimler,1,other,170000,Arka Frenin Servisi,0000614,İşçilik,00,00,0

In [79]:
df_1 = df[(df["ismalfunction"]==1)][["vehicleid", "invoicedate"]]
df_1

                  vehicleid          invoicedate
39       02i0Y00000FV2TpQAL  2020-06-01 00:00:00
157      02i1i00000EVV9aAAH  2021-10-25 00:00:00
516      02i0Y000004hHI3QAM  2020-10-31 00:00:00
692      02i0Y000009q89bQAA  2021-11-29 00:00:00
795      02i0Y00000G9myWQAR  2019-12-17 00:00:00
...                     ...                  ...
2047612  02i0Y000004iEE5QAM  2018-02-15 00:00:00
2047662  02i0Y000004hYsFQAU  2021-11-12 00:00:00
2047701  02i0Y00000G9n7sQAB  2019-11-15 00:00:00
2048038  02i0Y000007XiyCQAS  2019-09-20 00:00:00
2048054  02i0Y000004iE9KQAU  2021-04-13 00:00:00

[13352 rows x 2 columns]

In [82]:
df_1.groupby("vehicleid")["invoicedate"].count().sort_values()

vehicleid
02i0Y000004fqDZQAY     1
02i0Y000005DaO3QAK     1
02i0Y000005DaO8QAK     1
02i0Y000005DaODQA0     1
02i0Y000005DaOIQA0     1
                      ..
02i0Y000009q68gQAA    15
02i0Y00000G9m8VQAR    15
02i0Y000005HsLxQAK    15
02i0Y00000FTosIQAT    17
02i0Y000009q55WQAQ    20
Name: invoicedate, Length: 4979, dtype: int64

In [86]:
df_1.pivot_table(index=['vehicleid'],
                 values=['invoicedate'])
                 ,
#                  aggfunc='count')

C:\Users\Toshiba\AppData\Local\Temp\ipykernel_13412\64709702.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  df_1.pivot_table(index=['vehicleid'],

Empty DataFrame
Columns: []
Index: [02i0Y000004fqDZQAY, 02i0Y000004fqIdQAI, 02i0Y000004fqsDQAQ, 02i0Y000004fqt5QAA, 02i0Y000004fr1dQAA, 02i0Y000004fr4IQAQ, 02i0Y000004frG5QAI, 02i0Y000004frGnQAI, 02i0Y000004frHHQAY, 02i0Y000004frN6QAI, 02i0Y000004frTTQAY, 02i0Y000004frXaQAI, 02i0Y000004frc5QAA, 02i0Y000004frdwQAA, 02i0Y000004fruiQAA, 02i0Y000004fs1ZQAQ, 02i0Y000004fsEeQAI, 02i0Y000004fsFlQAI, 02i0Y000004fsI6QAI, 02i0Y000004fuXbQAI, 02i0Y000004fuY0QAI, 02i0Y000004fuYKQAY, 02i0Y000004fukaQAA, 02i0Y000004fvvSQAQ, 02i0Y000004fwajQAA, 02i0Y000004fxYvQAI, 02i0Y000004fxjIQAQ, 02i0Y000004fyT8QAI, 02i0Y000004fyxNQAQ, 02i0Y000004g0X1QAI, 02i0Y000004g0fDQAQ, 02i0Y000004g163QAA, 02i0Y000004g1UhQAI, 02i0Y000004g23jQAA, 02i0Y000004g3BaQAI, 02i0Y000004g3sBQAQ, 02i0Y000004g40RQAQ, 02i0Y000004g47aQAA, 02i0Y000004g4gXQAQ, 02i0Y000004g56AQAQ, 02i0Y000004g5zbQAA, 02i0Y000004g653QAA, 02i0Y000004g6CYQAY, 02i0Y000004g6vUQAQ, 02i0Y000004g7olQAA, 02i0Y000004g8D9QAI, 02i0Y000004g8J2QAI, 02i0Y000004g8JHQAY, 02i0Y000004g8YYQAY, 02i0Y000004g8djQAA, 02i0Y000004gz5aQAA, 02i0Y000004gz79QAA, 02i0Y000004gzO2QAI, 02i0Y000004gzOBQAY, 02i0Y000004gzSPQAY, 02i0Y000004gzhtQAA, 02i0Y000004gzmkQAA, 02i0Y000004gzwsQAA, 02i0Y000004gzzGQAQ, 02i0Y000004h0HfQAI, 02i0Y000004h0YtQAI, 02i0Y000004h0ghQAA, 02i0Y000004h0r5QAA, 02i0Y000004h0wtQAA, 02i0Y000004h11fQAA, 02i0Y000004h18iQAA, 02i0Y000004h1PWQAY, 02i0Y000004h1WVQAY, 02i0Y000004h1aRQAQ, 02i0Y000004h1acQAA, 02i0Y000004h1aeQAA, 02i0Y000004h1afQAA, 02i0Y000004h1ajQAA, 02i0Y000004h1dhQAA, 02i0Y000004h1e7QAA, 02i0Y000004h1e8QAA, 02i0Y000004h1eBQAQ, 02i0Y000004h1eDQAQ, 02i0Y000004h1eEQAQ, 02i0Y000004h1eGQAQ, 02i0Y000004h1fdQAA, 02i0Y000004h1gWQAQ, 02i0Y000004h1n0QAA, 02i0Y000004h1plQAA, 02i0Y000004h1tPQAQ, 02i0Y000004h1vuQAA, 02i0Y000004h1xxQAA, 02i0Y000004h20RQAQ, 02i0Y000004h24OQAQ, 02i0Y000004h281QAA, 02i0Y000004h2JeQAI, 02i0Y000004h2OuQAI, 02i0Y000004h2T2QAI, 02i0Y000004h2T3QAI, 02i0Y000004h2TyQAI, 02i0Y000004h2YcQAI, 02i0Y000004h2fvQAA, 02i0Y000004h2jMQAQ, 02i0Y000004h2nqQAA, 02i0Y000004h2otQAA, ...]

[4979 rows x 0 columns]

In [75]:
df_1.groupby(df_1.vehicleid)['invoicedate'].first()

vehicleid
02i0Y000004fqDZQAY    2019-05-13 00:00:00
02i0Y000004fqIdQAI    2019-11-07 00:00:00
02i0Y000004fqsDQAQ    2021-11-18 00:00:00
02i0Y000004fqt5QAA    2021-10-22 00:00:00
02i0Y000004fr1dQAA    2019-11-14 00:00:00
                             ...
02i1n00000OnyPVAAZ    2021-02-18 00:00:00
02i1n00000OoAQdAAN    2021-04-12 00:00:00
02i1n00000OolrGAAR    2021-09-27 00:00:00
02i1n00000OolrLAAR    2020-01-30 00:00:00
02i1n00000OolraAAB    2020-10-28 00:00:00
Name: invoicedate, Length: 4979, dtype: object

In [78]:
df_1.pivot_table(index=['vehicleid'],
                columns=["invoicedate"], 
                values=None,
                aggfunc='count')

                              bodycode                      \
invoicedate        2015-09-16 00:00:00 2015-10-28 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2015-11-19 00:00:00 2015-12-18 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2016-02-10 00:00:00 2016-02-29 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2016-03-07 00:00:00 2016-03-14 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            ...  \
invoicedate        2016-04-21 00:00:00 2016-05-30 00:00:00  ...
vehicleid                                                   ...
02i0Y000004fqDZQAY                 NaN                 NaN  ...
02i0Y000004fqIdQAI                 NaN                 NaN  ...
02i0Y000004fqsDQAQ                 NaN                 NaN  ...
02i0Y000004fqt5QAA                 NaN                 NaN  ...
02i0Y000004fr1dQAA                 NaN                 NaN  ...
...                                ...                 ...  ...
02i1n00000OnyPVAAZ                 NaN                 NaN  ...
02i1n00000OoAQdAAN                 NaN                 NaN  ...
02i1n00000OolrGAAR                 NaN                 NaN  ...
02i1n00000OolrLAAR                 NaN                 NaN  ...
02i1n00000OolraAAB                 NaN                 NaN  ...

                   subgroupdescription                      \
invoicedate        2021-12-21 00:00:00 2021-12-22 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2021-12-23 00:00:00 2021-12-24 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2021-12-25 00:00:00 2021-12-27 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

                                                            \
invoicedate        2021-12-28 00:00:00 2021-12-29 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN


invoicedate        2021-12-30 00:00:00 2021-12-31 00:00:00
vehicleid
02i0Y000004fqDZQAY                 NaN                 NaN
02i0Y000004fqIdQAI                 NaN                 NaN
02i0Y000004fqsDQAQ                 NaN                 NaN
02i0Y000004fqt5QAA                 NaN                 NaN
02i0Y000004fr1dQAA                 NaN                 NaN
...                                ...                 ...
02i1n00000OnyPVAAZ                 NaN                 NaN
02i1n00000OoAQdAAN                 NaN                 NaN
02i1n00000OolrGAAR                 NaN                 NaN
02i1n00000OolrLAAR                 NaN                 NaN
02i1n00000OolraAAB                 NaN                 NaN

[4979 rows x 26312 columns]